
  - name: Run MariaDB
    docker:
      image: "{{ mariadb_docker_username }}/{{ mariadb_docker_imagename }}"
      name: "{{ mariadb_docker_containername }}_server"
      volumes_from: "{{ mariadb_docker_containername }}_data"
      ports: "{{ mariadb_bind_address }}:{{ mariadb_port }}:3306"
      detach: yes
      env: 
        - mysql_root_password={{ mariadb_mysql_root_password }}
      state: running
    register: server_startup

  - name: Ensure MariaDB service is up 
    mysql_user:
      login_host: "{{ mariadb_bind_address }}"
      login_port: "{{ mariadb_port }}"
      login_user: root
      login_password: "{{ mariadb_mysql_root_password }}"
      name: root
      password: "{{ mariadb_mysql_root_password }}"
      host: localhost
      state: present
    register: server_connect
    until: server_connect|success
    retries: 30
    delay: 1


  - name: Add user into mariadb
    mysql_user:
      name: "{{item.name}}"
      password: "{{ mariadb_mysql_secret_password }}"
      host: "{{item.host | default('localhost')}}"
      priv: "{{item.priv}}"
      login_host: "{{ mariadb_bind_address }}"
      login_port: "{{ mariadb_port }}"
      login_user: root
      login_password: "{{ mariadb_mysql_root_password }}"
      state: present
    with_items: "{{mariadb_users}}"
    tags: mariadb

  
