
  - name: Run MariaDB
    docker_container:
      image: emmadxj/mariadb 
      name: mysql_server
      volumes_from: mysql_data
      ports: "3306:3306"
      state: started 

      #  - name: Ensure MariaDB service is up 
      #    mysql_user:
      #      login_host: localhost
      #      login_port: 3306
      #      login_user: root
      #      login_password: 
      #      name: root
      #      password: 
      #      host: localhost
      #      state: present
      #    register: server_connect
      #    until: server_connect|success
      #    retries: 30
      #    delay: 1
      #
      #  - name: update mariadb root password for local root account
      #    mysql_user: 
      #      name: root 
      #      host: localhost 
      #      password: ' ' 
      #      priv: "*.*:ALL,GRANT"
      #      state: present
      # 
      # 
      #  - name: update .my.cnf file with root password credentials
      #    template: 
      #      src: root/.my.cnf 
      #      dest: /root/.my.cnf 
      #      owner: root 
      #      group: root 
      #      mode: 0600
      # 
  - name: Add user into mariadb
    mysql_user:
      name: zamro
      password: "{{ mariadb_secret_password}}" 
      host: localhost
      priv: '*.*:ALL'
      login_host: localhost 
      login_port: 3306
      login_user: root
      login_password: "{{ mariadb_mysql_root_password }}" 
      state: present
    tags: mariadb

  
